services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: vladikshk
      POSTGRES_PASSWORD: password
      PGDATA: /home/vladikshk/postgres-data
    volumes:
      - postgres:/home/vladikshk/postgres-data
    ports:
      - "54320:5432"
    networks:
      - postgres
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.test
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  postgres:
    driver: bridge


volumes:
  postgres:
  pgadmin: